version: '3.0'

services:
  httpserver:
      image: dg-httpserver:latest 
    networks:
      default:
        aliases:
          - ditto-cluster
    entrypoint: sh -c "sleep 10000"


#  things:
#    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
#    networks:
#      default:
#        aliases:
#          - ditto-cluster
#    depends_on:
#      - policies
#    entrypoint: sh -c "sleep 10; java -jar /opt/ditto/starter.jar"
#    environment:
#      - TZ=Europe/Berlin
#      - INSTANCE_INDEX=1
#      - BIND_HOSTNAME=0.0.0.0
#      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
#      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
