version: '3.0'

services:
  httpserver:
      image: dg-httpserver:latest 
      networks:
        default:
          aliases:
            - ditto-cluster
      entrypoint: sh -c "sleep 10; /opt/dg/start.sh; sleep 10; java -jar /opt/dg/starter.jar"

  speed:
      image: dg-speed:latest 
      networks:
        default:
          aliases:
            - ditto-cluster
      entrypoint: sh -c "sleep 10; /opt/dg/start.sh; sleep 10; java -jar /opt/dg/starter.jar"
